### ISSUE TITLE
Rake command fails

### ISSUE THREAD

**Issue by ChaosCat** [ruboto/ruboto#777] opened 2015-12-24 20:07 UTC
I updated to the new version of Ruboto (and uninstalled all previous versions) the `rake` command fails to generate the APK seems to be having something to do with the ANT installation or the Rake gem itself (although I have the newest versions and the system paths are correctly set for each)
this how the build error looks like in CMD:

``` cmd
BUILD FAILED
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:888: The following error occurred while executing this line:
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:890: The following error occurred while executing this line:
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:902: The following error occurred while executing this line:
C:\Users\Job\Desktop\quick_start\build.xml:212: condition satisfied

Total time: 2 seconds
rake aborted!
Command failed with status (1): [ant.bat debug...]
C:/Users/Job/Desktop/quick_start/rakelib/ruboto.rake:972:in `build_apk'
C:/Users/Job/Desktop/quick_start/rakelib/ruboto.rake:555:in `block in <top (required)>'
Tasks: TOP => default => debug => C:/Users/Job/Desktop/quick_start/bin/QuickStart-debug.apk
(See full trace by running task with --trace)
```

and below is the full output with `--trace` option:

``` cmd
BUILD FAILED
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:888: The following error occurred while executing this line:
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:890: The following error occurred while executing this line:
C:\Users\Job\AppData\Local\Android\android-sdk\tools\ant\build.xml:902: The following error occurred while executing this line:
C:\Users\Job\Desktop\quick_start\build.xml:212: condition satisfied
        at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:164)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:124)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at com.android.ant.IfElseTask.execute(IfElseTask.java:120)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 1 second
rake aborted!
Command failed with status (1): [ant.bat -v debug...]
C:/Ruby22-x64/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
C:/Users/Job/Desktop/quick_start/rakelib/ruboto.rake:972:in `build_apk'
C:/Users/Job/Desktop/quick_start/rakelib/ruboto.rake:555:in `block in <top (required)>'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:238:in `call'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:238:in `block in execute'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:235:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:75:in `run'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
C:/Ruby22-x64/bin/rake:23:in `load'
C:/Ruby22-x64/bin/rake:23:in `<main>'
Tasks: TOP => default => debug => C:/Users/Job/Desktop/quick_start/bin/QuickStart-debug.apk
```

**Comment by donv** [comment] 2015-12-24 23:40
Hi @ChaosCat !

Thanks for the report!

So, it looks like the build failed in line 212 of `build.xml`.  That is where the `dex` operation signals failure with a non-zero exit code.  Right before this, it prints the output from the `dex` command, which should be the cause of your problem.

So, what is printed right before the `BUILD FAILED`line?

**Comment by ChaosCat** [comment] 2015-12-25 13:52
The maximum heap size is exceeded the maximum heap size allowed 
```cmd
-dex:
    [apply] Result: 1
     [echo] Error: Could not create the Java Virtual Machine.
     [echo] Error: A fatal exception has occurred. Program will exit.
     [echo] Invalid maximum heap size: -Xmx4096M
     [echo] The specified size exceeds the maximum representable size.
```

**Comment by ChaosCat** [comment] 2015-12-25 13:57
Is there a way to decrease the reserved memory for the VM by an argument or by editing the build.xml file?

**Comment by donv** [comment] 2015-12-25 21:42
Hi @ChaosCat !

Are you running on a 32 bit system?

You can specify the desired head size for the `dex` command by setting the `DX_HEAP_SIZE` system environment variable.  This is read here:  https://github.com/ruboto/ruboto/blob/1.4.0/assets/rakelib/ruboto.rake#L558

I would like to extract this into a setting in the `ruboto.yml` file.  It should be as easy as reading the `ruboto.yml` file and check if a setting, for example `dex_heap_size`, is set, and use that instead of the default.  You up for it?  Commit rights will be given if you implement this with a test on a fork.

**Comment by donv** [comment] 2015-12-25 21:52
Discussed earlier here:

* https://github.com/ruboto/ruboto/issues/749
* https://github.com/ruboto/ruboto/issues/668
* https://github.com/ruboto/ruboto/issues/478
* https://github.com/ruboto/ruboto/issues/405

https://github.com/ruboto/ruboto/search?q=dex+heap+size&type=Issues&utf8=%E2%9C%93

**Comment by donv** [comment] 2015-12-25 21:55
Added an issue for this:  https://github.com/ruboto/ruboto/issues/778

**Comment by donv** [comment] 2015-12-25 21:59
@ChaosCat Important!

The Rake task only INCREASES the dex heap size in the `dx` command script.  You need to manually lower it in the `dx` script file to make it lower than 4096.

**Comment by ChaosCat** [comment] 2015-12-26 09:14
I am running a 64 bit system, I tried setting the system environment variable manually to 2048 or even 1028 but with no success, same issue, same errors are thrown:
```CMD
-dex:
    [apply] Result: 1
     [echo] Error: Could not create the Java Virtual Machine.
     [echo] Error: A fatal exception has occurred. Program will exit.
     [echo] Invalid maximum heap size: -Xmx4096M
     [echo] The specified size exceeds the maximum representable size.
```
 I also tried adding logic for making sure the `MINIMUM_DEX_SIZE` can't be higher than 2048. didn't really help, it just keeps resetting it to 4096
BTW I have 4Gb RAM, maybe this is what's causing the issue?

**Comment by donv** [comment] 2023-05-08 13:31
Closing this issue since it relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.  A guide to getting started is in the README.

**Closed by donv** 2023-05-08 13:31 UTC
Labels: bug
