### ISSUE TITLE
New App with no custom code terminates directly after start (java.lang.NoSuchMethodException: makeDexElements).

### ISSUE THREAD

**Issue by hirschnase** [ruboto/ruboto#716] opened 2015-04-07 12:35 UTC
I want to learn Ruboto and tried to make first steps with Ruboto 1.3.0 and the newest Android SDK installed on OS X. I generated a new project with

ruboto gen app --package org.ruboto.example.quick_start --target 19

and then connect my Samsung S5 with Android 5.0 over USB and run

rake install start

The app compiles and is being deployed to the phone and then started.

What I did not expect is, that the app terminates immediately after the start. The logfile (rake log) shows me the following error(s):

20150407 142406.780765 I/ActivityManager(  922): Start proc org.ruboto.example.quick_start for activity org.ruboto.example.quick_start/.QuickStartActivity: pid=2205 uid=10478 gids={50478, 9997} abi=armeabi-v7a
20150407 142406.791696 I/SELinux ( 2205): Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_SM-G900F_4.4.2 ver=34
20150407 142406.791742 I/SELinux ( 2205): Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-G900F_5.0_0007
20150407 142406.792993 E/SELinux ( 2205): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
20150407 142406.793779 I/art     ( 2205): Late-enabling -Xcheck:jni
20150407 142406.810012 I/SurfaceFlinger(  252): id=3365 createSurf (1080x1920),1 flag=404, Starting org.ruboto.example.quick_start
20150407 142406.818517 D/TimaKeyStoreProvider( 2205): TimaSignature is unavailable
20150407 142406.818570 D/ActivityThread( 2205): Added TimaKeyStore provider
20150407 142407.118502 D/ResourcesManager( 2205): creating new AssetManager and set to /data/app/org.ruboto.example.quick_start-1/base.apk
20150407 142407.130078 I/art     ( 2205): Created application space /data/dalvik-cache/arm/data@app@org.ruboto.example.quick_start-1@base.apk@classes.dex.art at 0x76faf000~0x76fbb4b8
20150407 142407.131254 I/art     ( 2205): Loaded art file: /data/dalvik-cache/arm/data@app@org.ruboto.example.quick_start-1@base.apk@classes.dex.art
20150407 142407.144702 D/RUBOTO  ( 2205): EntryPointActivity onCreate:
20150407 142407.145440 I/Timeline( 2205): Timeline: Activity_launch_request id:org.ruboto.example.quick_start time:93735903
20150407 142407.146653 I/ActivityManager(  922): START u0 {cmp=org.ruboto.example.quick_start/org.ruboto.SplashActivity (has extras)} from uid 10478 on display 0
20150407 142407.158151 I/System.out( 2205): RubotoActivity onCreate(): org.ruboto.example.quick_start.QuickStartActivity, finishing: true
20150407 142407.158944 D/Activity( 2205): performCreate Call secproduct feature valuefalse
20150407 142407.158973 D/Activity( 2205): performCreate Call debug elastic valuetrue
20150407 142407.175500 D/RUBOTO  ( 2205): SplashActivity onCreate:
20150407 142407.176357 I/RUBOTO  ( 2205): SplashActivity Showing progress
20150407 142407.304824 D/OpenGLRenderer( 2205): Render dirty regions requested: true
20150407 142407.314270 D/Activity( 2205): performCreate Call secproduct feature valuefalse
20150407 142407.314306 D/Activity( 2205): performCreate Call debug elastic valuetrue
20150407 142407.315392 D/RUBOTO  ( 2205): SplashActivity onResume:
20150407 142407.315427 D/RUBOTO  ( 2205): Max memory: 512MB
20150407 142407.316051 D/RUBOTO  ( 2205): Setting up JRuby runtime (DEBUG)
20150407 142407.368972 D/DexDex  ( 2205): validateClassPath : []
20150407 142407.369857 D/DexDex  ( 2205): APK Date : 1428409425000 ,dexDir date : 1428409431000
20150407 142407.369921 D/DexDex  ( 2205): shouldDexOpt(/data/app/org.ruboto.example.quick_start-1/base.apk,/data/data/org.ruboto.example.quick_start/app_dexdex,[]) => false on Thread[Thread-98408,5,main]
20150407 142407.375153 E/AndroidRuntime( 2205): FATAL EXCEPTION: Thread-98408
20150407 142407.375188 E/AndroidRuntime( 2205): Process: org.ruboto.example.quick_start, PID: 2205
20150407 142407.375196 E/AndroidRuntime( 2205): java.lang.RuntimeException: java.lang.NoSuchMethodException: makeDexElements [class java.util.ArrayList, class java.io.File, class java.util.ArrayList]
20150407 142407.375202 E/AndroidRuntime( 2205): 	at org.ruboto.DexDex.appendOdexesToClassPath(DexDex.java:271)
20150407 142407.375209 E/AndroidRuntime( 2205): 	at org.ruboto.DexDex.validateClassPath(DexDex.java:158)
20150407 142407.375224 E/AndroidRuntime( 2205): 	at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:166)
20150407 142407.375235 E/AndroidRuntime( 2205): 	at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:123)
20150407 142407.375242 E/AndroidRuntime( 2205): 	at org.ruboto.SplashActivity$1.run(SplashActivity.java:78)
20150407 142407.375248 E/AndroidRuntime( 2205): 	at java.lang.Thread.run(Thread.java:818)
20150407 142407.375264 E/AndroidRuntime( 2205): Caused by: java.lang.NoSuchMethodException: makeDexElements [class java.util.ArrayList, class java.io.File, class java.util.ArrayList]
20150407 142407.375270 E/AndroidRuntime( 2205): 	at java.lang.Class.getDeclaredMethod(Class.java:635)
20150407 142407.375286 E/AndroidRuntime( 2205): 	at org.ruboto.FrameworkHack.appendDexListImplICS(FrameworkHack.java:145)
20150407 142407.375292 E/AndroidRuntime( 2205): 	at org.ruboto.DexDex.appendOdexesToClassPath(DexDex.java:260)
20150407 142407.375302 E/AndroidRuntime( 2205): 	... 5 more
20150407 142407.377064 V/ApplicationPolicy(  922): isApplicationStateBlocked userId 0 pkgname org.ruboto.example.quick_start
20150407 142407.381983 W/ActivityManager(  922):   Force finishing activity org.ruboto.example.quick_start/org.ruboto.SplashActivity
20150407 142407.388795 I/SurfaceFlinger(  252): id=3366 createSurf (193x193),1 flag=4, org.ruboto.example.quick_start/org.ruboto.SplashActivity
20150407 142407.405241 I/Adreno-EGL( 2205): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
20150407 142407.405301 I/Adreno-EGL( 2205): OpenGL ES Shader Compiler Version: E031.25.01.03
20150407 142407.405309 I/Adreno-EGL( 2205): Build Date: 10/28/14 Tue
20150407 142407.405316 I/Adreno-EGL( 2205): Local Branch: LA.BF.1.1_RB1_20141028_021_patches2
20150407 142407.405333 I/Adreno-EGL( 2205): Remote Branch:
20150407 142407.405340 I/Adreno-EGL( 2205): Local Patches:
20150407 142407.405346 I/Adreno-EGL( 2205): Reconstruct Branch:
20150407 142407.412818 I/OpenGLRenderer( 2205): Initialized EGL, version 1.4
20150407 142407.429539 I/OpenGLRenderer( 2205): HWUI protection enabled for context ,  &this =0xb3a22088 ,&mEglDisplay = 1 , &mEglConfig = 8
20150407 142407.430747 D/OpenGLRenderer( 2205): Enabling debug mode 0
20150407 142407.445914 I/SurfaceFlinger(  252): id=3367 createSurf (1080x1920),1 flag=404, org.ruboto.example.quick_start/org.ruboto.SplashActivity
20150407 142407.608902 D/RUBOTO  ( 2205): SplashActivity onPause:
20150407 142407.634617 D/CrashAnrDetector(  922): processName: org.ruboto.example.quick_start
20150407 142407.634671 D/CrashAnrDetector(  922): broadcastEvent : org.ruboto.example.quick_start data_app_crash
20150407 142407.686908 I/ActivityManager_SDHA(  922): F:057M, C:229M, ProcCnt:069, avgU:-----K, mgn:113M, nF:63580K, fd:19388K, thd:180M, wm:05M, c:01, e:07, lmkIdx:15, emS:00, rsmd:T_, lstCrt:org.ruboto.example.quick_start, TOP:MtpApplication, ear:0, car:0
20150407 142407.711302 I/SurfaceFlinger(  252): id=3369 createSurf (49x49),1 flag=4, Application Error: org.ruboto.example.quick_start
20150407 142408.152896 I/ActivityManager_SDHA(  922): F:065M, C:200M, ProcCnt:068, avgU:-----K, mgn:113M, nF:55152K, fd:04943K, thd:180M, wm:05M, c:01, e:07, lmkIdx:15, emS:00, rsmd:T_, lstCrt:org.ruboto.example.quick_start, TOP:teslacoilsw.launcher, ear:0, car:0
20150407 142408.170473 I/Timeline(  922): Timeline: Activity_windows_visible id: ActivityRecord{c06c023 u0 org.ruboto.example.quick_start/org.ruboto.SplashActivity t2532 f} time:93736928
20150407 142408.177116 I/SurfaceFlinger(  252): id=3365 Removed Starting org.ruboto.example.quick_start (8/11)
20150407 142408.178954 I/SurfaceFlinger(  252): id=3365 Removed Starting org.ruboto.example.quick_start (-2/11)
20150407 142408.187901 I/SurfaceFlinger(  252): id=3366 Removed org.ruboto.example.quick_start/org.ruboto.SplashActivity (7/10)
20150407 142408.187943 I/SurfaceFlinger(  252): id=3366 Removed org.ruboto.example.quick_start/org.ruboto.SplashActivity (-2/10)
20150407 142408.204844 I/SurfaceFlinger(  252): id=3367 Removed org.ruboto.example.quick_start/org.ruboto.SplashActivity (6/9)
20150407 142408.205641 I/SurfaceFlinger(  252): id=3367 Removed org.ruboto.example.quick_start/org.ruboto.SplashActivity (-2/9)
20150407 142408.222862 D/RUBOTO  ( 2205): SplashActivity onDestroy:
20150407 142408.223732 E/OpenGLRenderer( 2205): SFEffectCache:clear(), mSize = 0
20150407 142408.259812 E/WindowManager( 2205):
20150407 142408.259876 E/WindowManager( 2205): android.view.WindowLeaked: Activity org.ruboto.SplashActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{2a09f8fe V.E..... R......D 0,0-1002,348} that was originally added here
20150407 142408.259895 E/WindowManager( 2205): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:457)
20150407 142408.259914 E/WindowManager( 2205): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
20150407 142408.259922 E/WindowManager( 2205): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
20150407 142408.259929 E/WindowManager( 2205): 	at android.app.Dialog.show(Dialog.java:312)
20150407 142408.259936 E/WindowManager( 2205): 	at android.app.ProgressDialog.show(ProgressDialog.java:116)
20150407 142408.260012 E/WindowManager( 2205): 	at android.app.ProgressDialog.show(ProgressDialog.java:104)
20150407 142408.260029 E/WindowManager( 2205): 	at org.ruboto.SplashActivity.showProgress(SplashActivity.java:171)
20150407 142408.260047 E/WindowManager( 2205): 	at org.ruboto.SplashActivity.initJRuby(SplashActivity.java:75)
20150407 142408.260057 E/WindowManager( 2205): 	at org.ruboto.SplashActivity.onCreate(SplashActivity.java:43)
20150407 142408.260063 E/WindowManager( 2205): 	at android.app.Activity.performCreate(Activity.java:6221)
20150407 142408.260070 E/WindowManager( 2205): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
20150407 142408.260085 E/WindowManager( 2205): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
20150407 142408.260132 E/WindowManager( 2205): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
20150407 142408.260159 E/WindowManager( 2205): 	at android.app.ActivityThread.access$900(ActivityThread.java:172)
20150407 142408.260167 E/WindowManager( 2205): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
20150407 142408.260179 E/WindowManager( 2205): 	at android.os.Handler.dispatchMessage(Handler.java:102)
20150407 142408.260186 E/WindowManager( 2205): 	at android.os.Looper.loop(Looper.java:145)
20150407 142408.260203 E/WindowManager( 2205): 	at android.app.ActivityThread.main(ActivityThread.java:5834)
20150407 142408.260209 E/WindowManager( 2205): 	at java.lang.reflect.Method.invoke(Native Method)
20150407 142408.260216 E/WindowManager( 2205): 	at java.lang.reflect.Method.invoke(Method.java:372)
20150407 142408.260222 E/WindowManager( 2205): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
20150407 142408.260265 E/WindowManager( 2205): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
20150407 142409.589031 I/Process ( 2205): Sending signal. PID: 2205 SIG: 9
20150407 142409.612688 I/ActivityManager(  922): Process org.ruboto.example.quick_start (pid 2205)(adj 9) has died(84,191)
20150407 142409.668154 I/SurfaceFlinger(  252): id=3369 Removed Application Error: org.ruboto.example.quick_start (7/8)
20150407 142409.669307 I/SurfaceFlinger(  252): id=3369 Removed Application Error: org.ruboto.example.quick_start (-2/8)

I expected to see the standard "What hath Matz wrought?" screen as shown and explained in the tutorials. Please help! :)

Thanks, Marc

**Comment by donv** [comment] 2015-04-07 12:47
Hi @hirschnase !

Thanks for the report!  This is of course a bug.

Did this happen with an emulator as well?  You can start an emulator by running

    ruboto emulator

in your project directory.  Be sure to disconnect your phone when developing with an emulator.

**Comment by hirschnase** [comment] 2015-04-07 13:12
Hi @donv,

thanks for you fast response! After installing the RubotoCore-release-1.0.3.apk in the emulator, it works like expected! I installed Ruboto Core on my S5, but this does not make a difference.

**Comment by hirschnase** [comment] 2015-04-07 13:22
Btw the Ruboto Core App (v1.0.5) also terminates immediately when I start it on the Samsung S5 device...

**Comment by donv** [comment] 2015-04-07 22:47
I suspect this is a duplicate of issue #686 .

**Comment by hirschnase** [comment] 2015-04-08 07:32
Hmm, not sure. I did not put the core inside the app and I also do not see the 'Get Ruboto Core' image when I start the app. It just terminates. Let me know if I can help debug further or provide more information/help testing with my device.

**Comment by donv** [comment] 2015-12-15 11:25
Hi @hirschnase !

Looks like I have run into the same problem on one of my own apps.  Expect a fix or workaround soon.

**Comment by donv** [comment] 2015-12-16 11:14
This may be relevant:  https://android.googlesource.com/platform/frameworks/multidex/+/dd3cc22f2fbc8ea4dd5fa88978dc8d1ae5034bd9/library/src/android/support/multidex/MultiDex.java

**Comment by donv** [comment] 2015-12-18 20:49
Hi @hirschnase !

I think I have identified and fixed the problem.  Are you able to test it from the master source?

https://github.com/ruboto/ruboto#from-source

I would really appreciate getting a confirmation on this.

**Comment by donv** [comment] 2015-12-22 22:45
Hi @hirschnase !

This has now been fixed and will be in the upcoming Ruboto 1.3.2 release.

**Closed by donv** 2015-12-22 22:45 UTC
Labels: bug
