### ISSUE TITLE
ruboto setup - Java heap space (Java::JavaLang::OutOfMemoryError)

### ISSUE THREAD

**Issue by ZyzioZiom** [ruboto/ruboto#746] opened 2015-07-09 23:22 UTC
Hello,

When I'm trying to install ruboto components I'm getting OutOfMemoryError. How can I setup with parameters to set maximum size of memory?

patryk@patryk-Vostro1510:~$ ruboto setup
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Not found
Android Emulator         : Not found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

Android package installer not found.
Would you like to download and install it? (Y/n): y
F, [2015-07-10T00:56:09.281000 #12034] FATAL -- : Java heap space (Java::JavaLang::OutOfMemoryError)
org.jruby.util.ByteList.ensure(ByteList.java:340)
org.jruby.util.io.EncodingUtils.strBufCat(EncodingUtils.java:1042)
org.jruby.util.io.EncodingUtils.encCrStrBufCat(EncodingUtils.java:1127)
org.jruby.RubyString.cat19(RubyString.java:1374)
org.jruby.RubyString.cat19(RubyString.java:1363)
org.jruby.RubyString.append19(RubyString.java:2579)
org.jruby.RubyString.concat19(RubyString.java:2614)
org.jruby.RubyString$INVOKER$i$1$0$concat19.call(RubyString$INVOKER$i$1$0$concat19.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)
org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:135)
org.jruby.runtime.Block.yieldSpecific(Block.java:120)
rubyjit.Net::ReadAdapter$$call_block_6e6dce6d4beb9939f709f4f28c2879b2e5f479791462869878.__file__(/home/patryk/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/net/protocol.rb:395)
rubyjit.Net::ReadAdapter$$call_block_6e6dce6d4beb9939f709f4f28c2879b2e5f479791462869878.__file__(/home/patryk/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/net/protocol.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
rubyjit.Net::ReadAdapter$$\=\^\^_d0540b61039445f01e3634b29fce9b95538fc8f81462869878.__file__(/home/patryk/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/net/protocol.rb:386)
rubyjit.Net::ReadAdapter$$\=\^\^_d0540b61039445f01e3634b29fce9b95538fc8f81462869878.__file__(/home/patryk/.rvm/rubies/jruby-1.7.19/lib/ruby/1.9/net/protocol.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)
org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.ast.WhileNode.interpret(WhileNode.java:131)

**Comment by ZyzioZiom** [comment] 2015-07-10 08:36
Android Studio installed successfully, so I could use it's installed SDKs. How to point Ruboto to these SDKs so it can recognize everything is installed?

**Comment by gfowley** [comment] 2015-07-10 21:48
With the SDK installed with Android Studio, I would proceed like this:

Logout and login again to ensure all changes to your environment take effect.

Locate the Android SDK installation path (you may have environment variable ANDROID_HOME set):
```shell
gerard@wonko:~$ echo $ANDROID_HOME
/home/gerard/android-sdk-linux/
```

Verify that the Android SDK directories are in your path:
```shell
echo $PATH
... /home/gerard/android-sdk-linux/tools ...
... /home/gerard/android-sdk-linux/platform-tools ...
... /home/gerard/android-sdk-linux/build-tools/22.0.1 ...
```

Verify that the Android SDK utilities are executed from the expected locations:
```shell
gerard@wonko:~$ which aapt
/home/gerard/android-sdk-linux/build-tools/22.0.1/aapt
gerard@wonko:~$ which adb
/home/gerard/android-sdk-linux/platform-tools/adb
gerard@wonko:~$ which android
/home/gerard/android-sdk-linux/tools/android
```

Verify your Ruby environment is good. Use something like RVM to install JRuby and also create a fresh gemset dedicated for you project, then `gem install ruboto`.
 
Run `ruboto setup` again to verify all SDK dependencies are satisfied. 

Assuming you're using Bash, you should end up with a `~/.rubotorc` file that looks something like this:
```shell
PATH="/home/gerard/android-sdk-linux/build-tools/22.0.1:$PATH"
PATH="/home/gerard/android-sdk-linux/platform-tools:$PATH"
PATH="/home/gerard/android-sdk-linux/tools:$PATH"
```

File `~/.rubotorc` should be sourced from `~./bashrc`:
```shell
# rubotorc adds android sdk to path
# BEGIN Ruboto setup
source ~/.rubotorc
# END Ruboto setup
```

It may also help to define ANDROID_HOME in `~./bashrc`:
```shell
export ANDROID_HOME=/home/gerard/android-sdk-linux/
```

Logout and login again to ensure all changes to your environment take effect.

**Comment by ZyzioZiom** [comment] 2015-07-12 10:52
Works! Thanks :)

**Comment by donv** [comment] 2015-07-12 21:25
@gfowley seems like this one is solved.  Assign it to yourself and close it.  I already added the "support" tag to indicate it is not a bug, and added it to the upcoming 1.3.1 release.

**Closed** 2015-07-12 22:06 UTC
Labels: support
