### ISSUE TITLE
"--with-jruby" seems to do its job, but then I still need to download and install Ruboto Core on device

### ISSUE THREAD

**Issue by jjgh** [ruboto/ruboto#655] opened 2014-07-30 03:19 UTC
Hello, I am creating a new app with:
```
ruboto gen app --package org.ruboto.example.playground  --name Playground --target android-18 --with-jruby 1.7.13
```
This correctly copies "jruby-core-1.7.13.jar" and "jruby-stdlib-1.7.13.jar" in "/libs" folder together with a "dx.jar" and a "/tmp" subfolder.

Later I complile and install with: "rake install" but then, when I clilck on the app in my device (GenyMotion virtual device) it still asks me to download and install Ruboto Core. Shouldn't "--with-jruby" avoid just that by including the jruby jars? Or am I missing something?

My environment is: 
jruby 1.7.13 (1.9.3p392) 2014-06-24 43f133c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_60-b19 [Windows 7-amd64]

Edit: probably not related to this but maybe worth pointing out: after installing Ruboto Core my app crashes on the Genymotion virtual device (api level 18, Android 4.3) as soon as I run it (well after the 5-6 seconds needed to load the Ruboto environment), while on my 4.4 Android smartphone it runs ok.

Thanks

**Comment by jjgh** [comment] 2015-01-19 12:59
@matthewblott in my case it was caused by long path names, check my full answer above, does this fix it for you?

**Comment by donv** [comment] 2015-04-05 09:04
Hi all!

I am releasing Ruboto 1.3.0 later today.  Could you try it and see if you still have the problem?

**Comment by bromine0x23** [comment] 2015-04-08 15:55
It seems caused by the path format between Windows and UNIX-like systems. I notice that "bin\dexedLibs" directory is empty, so I guess it's some wrong when building.

So I check and modify the `build.xml#169` which content is
```
<mapper id="pre-dex-mapper" type="glob" from="libs/*.jar" to="bin/dexedLibs/*-dexed.jar"/>
```
to
```
<mapper id="pre-dex-mapper" type="glob" from="libs\*.jar" to="bin/dexedLibs\*-dexed.jar"/>
```
Then everthing is OK.

**Comment by KCErb** [comment] 2015-06-21 00:11
Hey @jjgh, I know this is an old thread but I didn't see another way of contacting you. I'm curious: how are you using Genymotion with Ruboto? I tried dragging an apk to the emulator but it wouldn't go. Any tips?

**Comment by donv** [comment] 2015-12-22 23:23
Hi all!

Ruboto 1.3.2 will be released this week.  Is there anything we need to do regarding this issue?

**Comment by jjgh** [comment] 2015-12-23 11:38
@KCErb if I remember correctly, you have to do "rake install" to compile and install the application.

**Comment by donv** [comment] 2015-12-23 12:15
So, this seems resolved.

**Closed by donv** 2015-12-23 12:15 UTC
Labels: bug, help wanted, Java
